### ISSUE TITLE
Handle authorization in Middleware

### ISSUE THREAD

**Issue by fluid-movement** [freestyle-players-association/fpa-app#11]
Create a robust system for redirecting users from pages they are not supposed to be on.

Example:
PATH: "/tournaments/<tournament_id>/schedule/create"

Only users who are organizers of the tournament, should be able to call this page. Otherwise redirect the user to "/tournaments/<tournament_id>/schedule", maybe with a message.

The Nextjs Middleware would be the best place for this. I imagine a map of regexes, and a handler method. I guess there might already be best practices or ready made solutions here.

**Comment by zzZCodeZzz** [comment]
yes, already did that.
in some cases, depending on what we want, it can be a little troubblesome in combination with internationalization.
But maybe they already fixed that.

**Comment by fdnklg** [comment]
Why do we need internationalisation?

**Comment by zzZCodeZzz** [comment]
already setup
