### ISSUE TITLE
Create "update" and "delete" actions

### ISSUE THREAD

**Issue by fluid-movement** [freestyle-players-association/fpa-app#13]
Our entities need update and delete actions.

*Big request* Find some way of creating generic methods for this, so we don't need to create huge amounts of code for this. 
This would be a good time to refactor the create methods to reduce duplicate code and make the creation of future entities easier.

**Comment by zzZCodeZzz** [comment]
I think for most usecases we don't need endpoints.
Keep in mind that we use rls for authorization (who is allowed).
So the most complex part about the update and deletion is the rls.
The rest will be using the supabase api (abstraction) to make a query to update or delete.

Don't get me wrong, I love abstractions, but here I don't think we need one yet.

Maybe I don't see something here. If so, pls provide an example of an absraction that you thought of.

**Comment by fluid-movement** [comment]
Agreed, we can use the current patterns
