### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by fluid-movement** [freestyle-players-association/fpa-app#16]
Lets start thinking about how to make our application available in multiple languages.

This should be an application for the global community, so everyone should be able to use it in their preferred language.

**Comment by zzZCodeZzz** [comment]
I personally see this as a "nice to have in the late future feature".
Everybody in the community speaks english, we communicate in english all the time.
By adding internationalization now, we would be adding a feature that we don't need at this moment for the community.

**Comment by fdnklg** [comment]
I agree with Manu. English is the shared language. Adding another layer adds another bulk of translation work to provide the content in several language.
