### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by PatrykMilczarek** [freestyle-players-association/fpa-app#41]
I think this file should be updated to reflect more accurately the steps required to run the app locally.
I, myself had to do some extra steps that were not listed in the instruction, like downloading Docker Desktop, also it was not so clear to me which URL to copy for NEXT_PUBLIC_SUPABASE_URL but I guessed it should be  API URL.

Also there are some additional settings required to do in Docker Desktop to run supabase without errors.
https://supabase.com/docs/guides/cli/getting-started?queryGroups=platform&platform=windows

**Comment by fluid-movement** [comment]
Great idea, seeing as you just did it, could you update the readme?
