### ISSUE TITLE
Rename tournament entity

### ISSUE THREAD

**Issue by fluid-movement** [freestyle-players-association/fpa-app#6]
I would like to rename tournament to "event". Not every frisbee event is a tournament, event sound friendlier. We have two options:

- Keep the backend naming as tournament, only use event on all frontend facing things like text and routing
- completely refactor everything. So that would also include renaming database tables

We are currently at the beginning of development, now would be the right time to do this.

**Comment by zzZCodeZzz** [comment]
agreed
